stages:
  - build-image

variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive
  
build_service_image:
   stage: build-image
   image: docker:19
   services:
     - docker:19-dind
   script:
     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
     - docker pull $CI_REGISTRY_IMAGE:latest_service || true
     - >
       docker build
       --pull
       --build-arg http_proxy=$http_proxy
       --build-arg https_proxy=$https_proxy
       --build-arg no_proxy=$no_proxy
       --build-arg VCS_REF=$CI_COMMIT_SHA
       --build-arg VCS_URL=$CI_PROJECT_URL
       --cache-from $CI_REGISTRY_IMAGE:latest_service
       --tag $CI_REGISTRY_IMAGE:latest_service
       -f service.dockerfile .
     - docker push $CI_REGISTRY_IMAGE:latest_service

build_enketo_image:
   stage: build-image
   image: docker:19
   services:
     - docker:19-dind
   script:
     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
     - docker pull $CI_REGISTRY_IMAGE:latest_enketo || true
     - >
       docker build
       --pull
       --build-arg http_proxy=$http_proxy
       --build-arg https_proxy=$https_proxy
       --build-arg no_proxy=$no_proxy
       --build-arg VCS_REF=$CI_COMMIT_SHA
       --build-arg VCS_URL=$CI_PROJECT_URL
       --cache-from $CI_REGISTRY_IMAGE:latest_enketo
       --tag $CI_REGISTRY_IMAGE:latest_enketo
       -f enketo.dockerfile .
     - docker push $CI_REGISTRY_IMAGE:latest_enketo
